import Head from "next/head";
import Image from "next/image";
import { About, Contact, Main, Navbar, Projects, Skills } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Moataz | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
